module.exports = {
  apps: [
    {
      name: "metrik-backend",
      script: "/home/sgpme/app/backend/start.sh",
      cwd: "/home/sgpme/app/backend",
      exec_mode: "fork",
      interpreter: "bash",
      max_memory_restart: "500M",
      error_file: "/home/sgpme/app/logs/backend-error.log",
      out_file: "/home/sgpme/app/logs/backend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
    },
    {
      name: "metrik-frontend",
      script: "npm",
      args: "start",
      cwd: "/home/sgpme/app/frontend",
      exec_mode: "fork",
      env: {
        PORT: "3030",
        NODE_ENV: "production",
      },
      max_memory_restart: "300M",
      error_file: "/home/sgpme/app/logs/frontend-error.log",
      out_file: "/home/sgpme/app/logs/frontend-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
    },
    {
      name: "metrik-webhook",
      script: "/home/sgpme/app/webhook-server.js",
      cwd: "/home/sgpme/app",
      exec_mode: "fork",
      interpreter: "node",
      max_memory_restart: "100M",
      error_file: "/home/sgpme/app/logs/webhook-error.log",
      out_file: "/home/sgpme/app/logs/webhook-out.log",
      log_date_format: "YYYY-MM-DD HH:mm:ss Z",
      merge_logs: true,
      autorestart: true,
    },
  ],
};
